name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
  # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the main branch
    - uses: actions/checkout@v2
    
    # sets up .NET Core SDK 6.0.x
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
        
    # Install dotnet wasm buildtools workload
    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools
      
    # Publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish TCITR-website/TCITR-website.csproj -c:Release -p:GHPages=true -o dist/Web --nologo
      
    # changes the base-tag in index.html from '/' to 'TCITR-website' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to TCITR-website
      run: sed -i 's/<base href="\/" \/>/<base href="\/TCITR-website\/" \/>/g' release/wwwroot/index.html
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist/Web/wwwroot
